services:
    app:
      build: .
      ports:
        - "8080:8080"
      environment:
        - JWT_SECRET=${JWT_SECRET}
        - SPRING_DATA_REDIS_HOST=redis
        - SPRING_MONGODB_URI=mongodb://mongo:27017/spboot
        - SPRING_RABBITMQ_HOST=rabbitmq
        - SPRING_RABBITMQ_PORT=5672
        - SPRING_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
        - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}

      depends_on:
        mongo:
          condition: service_healthy
        redis:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy

    mongo:
      image: mongo:7
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      healthcheck:
        test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
        interval: 10s
        timeout: 5s
        retries: 5

    redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
    
    rabbitmq:
      image: rabbitmq:4-management
      ports:
        - "15672:15672"
        - "5672:5672"
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      volumes:
        - rabbit_data:/var/lib/rabbitmq
      healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5


volumes:
  mongo_data:
  rabbit_data: