spring.application.name=spboot
jwt.secret=supersecretkeysupersecretkeysupersecretkey
cors.origin=http://localhost:5173
ratelimit.login.capacity=5
ratelimit.login.fillRate=5
ratelimit.login.window=1m
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.mongodb.uri=mongodb://mongo:27017/spboot
