package com.example.spboot.exception;

public enum ErrorCode {
    USER_EXISTS,
    NOT_FOUND,
    FORBIDDEN,
    INVALID_REFRESH_TOKEN,
    UNAUTHENTICATED,
    TOKEN_EXPIRED,
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    CSRF_INVALID,
    VALIDATION_FAILED,
    RATE_LIMITED
}
